//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Modules.OrientalSails.Web.Admin {
    
    
    public partial class QuotationView {
        
        /// <summary>
        /// txtOs2d1nDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs2d1nDouble;
        
        /// <summary>
        /// txtOs2d1nSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs2d1nSingle;
        
        /// <summary>
        /// txtOs2d1nChildren6to11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs2d1nChildren6to11;
        
        /// <summary>
        /// txtOs12d1nCharter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs12d1nCharter;
        
        /// <summary>
        /// txtOs22d1nCharter1to4passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs22d1nCharter1to4passenger;
        
        /// <summary>
        /// txtOs22d1nCharter5to8passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs22d1nCharter5to8passenger;
        
        /// <summary>
        /// txtOs22d1nCharter9to12passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs22d1nCharter9to12passenger;
        
        /// <summary>
        /// txtOs22d1nCharter13to17passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs22d1nCharter13to17passenger;
        
        /// <summary>
        /// txtOs3d2nDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs3d2nDouble;
        
        /// <summary>
        /// txtOs3d2nSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs3d2nSingle;
        
        /// <summary>
        /// txtOs3d2nChildren6to11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs3d2nChildren6to11;
        
        /// <summary>
        /// txtOs13d2nCharter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs13d2nCharter;
        
        /// <summary>
        /// txtOs23d2nCharter1to4passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs23d2nCharter1to4passenger;
        
        /// <summary>
        /// txtOs23d2nCharter5to8passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs23d2nCharter5to8passenger;
        
        /// <summary>
        /// txtOs23d2nCharter9to12passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs23d2nCharter9to12passenger;
        
        /// <summary>
        /// txtOs23d2nCharter13to17passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtOs23d2nCharter13to17passenger;
        
        /// <summary>
        /// txtCls2d1nDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtCls2d1nDouble;
        
        /// <summary>
        /// txtCls2d1nSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtCls2d1nSingle;
        
        /// <summary>
        /// txtCls2d1nChildren6to11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtCls2d1nChildren6to11;
        
        /// <summary>
        /// txtCls2d1nCharter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtCls2d1nCharter;
        
        /// <summary>
        /// txtCls3d2nDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtCls3d2nDouble;
        
        /// <summary>
        /// txtCls3d2nSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtCls3d2nSingle;
        
        /// <summary>
        /// txtCls3d2nChildren6to11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtCls3d2nChildren6to11;
        
        /// <summary>
        /// txtCls3d2nCharter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtCls3d2nCharter;
        
        /// <summary>
        /// txtStl2d1nDeluxeDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nDeluxeDouble;
        
        /// <summary>
        /// txtStl2d1nDeluxeSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nDeluxeSingle;
        
        /// <summary>
        /// txtStl2d1nDeluxeExtrabed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nDeluxeExtrabed;
        
        /// <summary>
        /// txtStl2d1nExecutiveDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nExecutiveDouble;
        
        /// <summary>
        /// txtStl2d1nExecutiveSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nExecutiveSingle;
        
        /// <summary>
        /// txtStl2d1nExecutiveExtrabed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nExecutiveExtrabed;
        
        /// <summary>
        /// txtStl2d1nSuiteDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nSuiteDouble;
        
        /// <summary>
        /// txtStl2d1nSuiteSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nSuiteSingle;
        
        /// <summary>
        /// txtStl2d1nSuiteExtrabed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nSuiteExtrabed;
        
        /// <summary>
        /// txtStl2d1nCharter1to40passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nCharter1to40passenger;
        
        /// <summary>
        /// txtStl2d1nCharter41to50passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nCharter41to50passenger;
        
        /// <summary>
        /// txtStl2d1nCharter51to63passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl2d1nCharter51to63passenger;
        
        /// <summary>
        /// txtStl3d2nDeluxeDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nDeluxeDouble;
        
        /// <summary>
        /// txtStl3d2nDeluxeSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nDeluxeSingle;
        
        /// <summary>
        /// txtStl3d2nDeluxeExtrabed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nDeluxeExtrabed;
        
        /// <summary>
        /// txtStl3d2nExecutiveDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nExecutiveDouble;
        
        /// <summary>
        /// txtStl3d2nExecutiveSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nExecutiveSingle;
        
        /// <summary>
        /// txtStl3d2nExecutiveExtrabed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nExecutiveExtrabed;
        
        /// <summary>
        /// txtStl3d2nSuiteDouble control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nSuiteDouble;
        
        /// <summary>
        /// txtStl3d2nSuiteSingle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nSuiteSingle;
        
        /// <summary>
        /// txtStl3d2nSuiteExtrabed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nSuiteExtrabed;
        
        /// <summary>
        /// txtStl3d2nCharter1to40passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nCharter1to40passenger;
        
        /// <summary>
        /// txtStl3d2nCharter41to50passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nCharter41to50passenger;
        
        /// <summary>
        /// txtStl3d2nCharter51to63passenger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal txtStl3d2nCharter51to63passenger;
    }
}
